"""empty message

Revision ID: a734881592c3
Revises: 
Create Date: 2022-04-28 16:58:45.223358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a734881592c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('issue', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('staff', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('discount', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cardnum', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scooters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.Column('LocationID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['LocationID'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ScooterID', sa.Integer(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('numHours', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('option', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ScooterID'], ['scooters.id'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('scooters')
    op.drop_table('cards')
    op.drop_table('users')
    op.drop_table('reports')
    op.drop_table('prices')
    op.drop_table('locations')
    # ### end Alembic commands ###
